name: Feature request
description: Suggest an idea, reaction or integration
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would it be useful?
  - type: checkboxes
    id: help
    attributes:
      label: Contributing
      options:
        - label: I'd like to work on this myself
