// channel names
export const IPC = {
  input: 'critter:input',
  cursor: 'critter:cursor',
  agent: 'critter:agent',
  reminder: 'critter:reminder',
  pomodoro: 'critter:pomodoro',
  settings: 'critter:settings',
  peek: 'critter:peek',
  getSettings: 'critter:get-settings',
  setSettings: 'critter:set-settings',
  setInteractive: 'critter:set-interactive',
  dragStart: 'critter:drag-start',
  dragMove: 'critter:drag-move',
  dragEnd: 'critter:drag-end',
  openSettings: 'critter:open-settings',
  contextMenu: 'critter:context-menu',
  pomodoroCmd: 'critter:pomodoro-cmd',
  agentStatus: 'critter:agent-status',
  installAgent: 'critter:install-agent',
  uninstallAgent: 'critter:uninstall-agent',
  testEvent: 'critter:test-event',
  testReminder: 'critter:test-reminder',
  exportSettings: 'critter:export-settings',
  importSettings: 'critter:import-settings',
} as const;
