import { app, Menu, nativeImage, Tray, type MenuItemConstructorOptions } from 'electron';
import { join } from 'node:path';
import type { CharacterId } from '../shared/types';
import {
  isPeeking,
  isReactionsPaused,
  onStateChange,
  pomodoroCommand,
  togglePeek,
  toggleReactionsPaused,
} from './hooks';
import { getSettings, onSettingsChanged, updateSettings } from './store';
import { toggleCompanionVisible } from './windows/overlay';
import { openSettings } from './windows/settings';

/** Tray PNGs are generated by tools/make_icons.py into resources/tray (bundled in the asar). */
export function trayIconPath(
  character: CharacterId,
  platform: string = process.platform,
  appPath: string = app.getAppPath(),
): string {
  const dir = join(appPath, 'resources', 'tray');
  // macOS: monochrome template image (auto @2x); Windows: 16px (+@2x); Linux: 32px.
  if (platform === 'darwin') return join(dir, `${character}Template.png`);
  return join(dir, `${character}-${platform === 'win32' ? 16 : 32}.png`);
}

export function makeTrayIcon(character: CharacterId = getSettings().character): Electron.NativeImage {
  const img = nativeImage.createFromPath(trayIconPath(character));
  if (process.platform === 'darwin') img.setTemplateImage(true);
  return img;
}

export function buildMenu(): Menu {
  const s = getSettings();
  const char = (id: CharacterId, label: string): MenuItemConstructorOptions => ({
    label,
    type: 'radio',
    checked: s.character === id,
    click: () => updateSettings({ character: id }),
  });
  return Menu.buildFromTemplate([
    { label: 'Character', enabled: false },
    char('stitch', 'Stitch'),
    char('yoda', 'Yoda'),
    { type: 'separator' },
    {
      label: 'Pomodoro',
      submenu: [
        { label: 'Start', click: () => pomodoroCommand('start') },
        { label: 'Pause', click: () => pomodoroCommand('pause') },
        { label: 'Resume', click: () => pomodoroCommand('resume') },
        { label: 'Skip phase', click: () => pomodoroCommand('skip') },
        { label: 'Stop', click: () => pomodoroCommand('stop') },
      ],
    },
    { label: 'Peek mode', type: 'checkbox', checked: isPeeking(), click: togglePeek },
    {
      label: 'Pause reactions',
      type: 'checkbox',
      checked: isReactionsPaused(),
      click: toggleReactionsPaused,
    },
    {
      label: 'Mute',
      type: 'checkbox',
      checked: !s.sound.enabled,
      click: () => updateSettings({ sound: { ...s.sound, enabled: !getSettings().sound.enabled } }),
    },
    {
      label: 'Hide / show companion',
      click: toggleCompanionVisible,
    },
    { type: 'separator' },
    { label: 'Settings…', click: openSettings },
    { label: 'Quit CodeCritter', click: () => app.quit() },
  ]);
}

/** Native popup used by the overlay's right-click (IPC.contextMenu). */
export function popupMenu(): void {
  buildMenu().popup();
}

let tray: Tray | null = null;

export function createTray(): Tray {
  tray = new Tray(makeTrayIcon());
  tray.setToolTip('CodeCritter');
  let iconFor = getSettings().character;
  const refresh = (): void => {
    const c = getSettings().character;
    if (c !== iconFor) {
      iconFor = c;
      tray?.setImage(makeTrayIcon(c));
    }
    tray?.setContextMenu(buildMenu());
  };
  refresh();
  onSettingsChanged(refresh);
  onStateChange(refresh);
  tray.on('double-click', openSettings);
  return tray;
}
