//! Settings persistence: `settings.json` in `app_config_dir`, deep-merged onto the embedded
//! defaults (`src/shared/defaults.json`, generated by `npm run gen:defaults`).

use crate::state::AppState;
use serde_json::{json, Map, Value};
use std::path::PathBuf;
use tauri::{AppHandle, Emitter, Manager};

pub const EVT_SETTINGS: &str = "critter:settings";
const DEFAULTS_JSON: &str = include_str!("../../src/shared/defaults.json");

pub fn defaults() -> Value {
    serde_json::from_str(DEFAULTS_JSON).expect("src/shared/defaults.json is valid JSON")
}

/// Deep merge `patch` onto `base`: objects merge key by key, arrays/primitives/null replace.
pub fn deep_merge(base: &mut Value, patch: &Value) {
    match (base, patch) {
        (Value::Object(b), Value::Object(p)) => {
            for (k, v) in p {
                match b.get_mut(k) {
                    Some(slot) => deep_merge(slot, v),
                    None => {
                        b.insert(k.clone(), v.clone());
                    }
                }
            }
        }
        (slot, v) => *slot = v.clone(),
    }
}

fn clamp(n: f64, lo: f64, hi: f64) -> f64 {
    if n.is_finite() {
        n.max(lo).min(hi)
    } else {
        lo
    }
}

/// JSON number, integral values stay integers (`1` not `1.0`).
fn jnum(n: f64) -> Value {
    if n.fract() == 0.0 && n.abs() < 1e15 {
        json!(n as i64)
    } else {
        json!(n)
    }
}

fn num(v: Option<&Value>, fallback: f64) -> f64 {
    v.and_then(Value::as_f64).unwrap_or(fallback)
}

/// Range validation / normalisation (scale 1-4 integer, opacity 0.2-1, volume 0-1, overheatKps 1-30).
pub fn validate(s: &mut Value) {
    let Some(o) = s.as_object_mut() else { return };
    let scale = clamp(num(o.get("scale"), 2.0), 1.0, 4.0).round();
    o.insert("scale".into(), json!(scale as i64));
    let op = clamp(num(o.get("opacity"), 1.0), 0.2, 1.0);
    o.insert("opacity".into(), jnum(op));
    let kps = clamp(num(o.get("overheatKps"), 8.0), 1.0, 30.0);
    o.insert("overheatKps".into(), jnum(kps));
    if let Some(Value::Object(up)) = o.get_mut("updates") {
        if !up.get("auto").map(Value::is_boolean).unwrap_or(false) {
            up.insert("auto".into(), json!(true));
        }
    }
    if let Some(Value::Object(snd)) = o.get_mut("sound") {
        let vol = clamp(num(snd.get("volume"), 0.5), 0.0, 1.0);
        snd.insert("volume".into(), jnum(vol));
    }
}

/// Migration hook (v1 is current). Always returns an object.
pub fn migrate(raw: Value) -> Value {
    if raw.is_object() {
        raw
    } else {
        Value::Object(Map::new())
    }
}

/// migrate -> deep-merge onto defaults -> validate.
pub fn load_from(raw: Value) -> Value {
    let mut s = defaults();
    deep_merge(&mut s, &migrate(raw));
    validate(&mut s);
    s
}

fn path(app: &AppHandle) -> Option<PathBuf> {
    app.path().app_config_dir().ok().map(|d| d.join("settings.json"))
}

fn write(app: &AppHandle, s: &Value) {
    let Some(p) = path(app) else { return };
    if let Some(dir) = p.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    let tmp = p.with_extension("json.tmp");
    if let Ok(text) = serde_json::to_string_pretty(s) {
        if std::fs::write(&tmp, text).is_ok() {
            let _ = std::fs::rename(&tmp, &p);
        }
    }
}

/// Load settings from disk into `AppState` (call once in setup, after `manage`).
pub fn init(app: &AppHandle) {
    let raw = path(app)
        .and_then(|p| std::fs::read_to_string(p).ok())
        .and_then(|t| serde_json::from_str::<Value>(t.strip_prefix('\u{feff}').unwrap_or(&t)).ok())
        .unwrap_or(Value::Null);
    let s = load_from(raw);
    write(app, &s);
    *app.state::<AppState>().settings.write() = s;
}

pub fn get(app: &AppHandle) -> Value {
    app.state::<AppState>().settings.read().clone()
}

/// Convenience: read a value by JSON pointer (e.g. `"/peek/edge"`).
pub fn get_ptr(app: &AppHandle, ptr: &str) -> Value {
    app.state::<AppState>()
        .settings
        .read()
        .pointer(ptr)
        .cloned()
        .unwrap_or(Value::Null)
}

pub fn scale(app: &AppHandle) -> i64 {
    get_ptr(app, "/scale").as_i64().unwrap_or(2).clamp(1, 4)
}

fn changed(a: &Value, b: &Value, keys: &[&str]) -> bool {
    keys.iter().any(|k| a.get(k) != b.get(k))
}

/// Deep-merge `patch`, validate, persist, emit `critter:settings` to every window and run hooks.
/// Never call while holding the settings lock.
pub fn update(app: &AppHandle, patch: Value) -> Value {
    let (prev, next) = {
        let st = app.state::<AppState>();
        let mut w = st.settings.write();
        let prev = w.clone();
        let mut next = prev.clone();
        deep_merge(&mut next, &patch);
        validate(&mut next);
        *w = next.clone();
        (prev, next)
    };
    write(app, &next);
    let _ = app.emit(EVT_SETTINGS, &next);

    if prev.get("scale") != next.get("scale") {
        crate::winmgr::apply_scale(app, next["scale"].as_i64().unwrap_or(2));
    }
    if prev.get("autostart") != next.get("autostart") {
        crate::autostart::apply(app, next["autostart"].as_bool().unwrap_or(false));
    }
    if changed(&prev, &next, &["character", "sound"]) {
        crate::tray::refresh(app);
    }
    let ag = |v: &Value| (v.pointer("/agents/enabled").cloned(), v.pointer("/agents/port").cloned());
    if ag(&prev) != ag(&next) {
        crate::agents::restart(app);
    }
    if changed(&prev, &next, &["reminders", "pomodoro", "messages", "dnd"]) {
        crate::scheduler::on_settings_changed(app);
    }
    crate::sync::on_settings_changed(app);
    next
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_parse_and_validate_clean() {
        let mut d = defaults();
        let before = d.clone();
        validate(&mut d);
        assert_eq!(d, before);
        assert_eq!(d["scale"], 2);
        assert_eq!(d["character"], "stitch");
    }

    #[test]
    fn deep_merge_objects_replace_arrays_and_null() {
        let mut base = json!({"a":{"x":1,"y":2},"arr":[1,2],"pos":{"x":1}});
        deep_merge(&mut base, &json!({"a":{"y":3},"arr":[9],"pos":null,"new":true}));
        assert_eq!(base, json!({"a":{"x":1,"y":3},"arr":[9],"pos":null,"new":true}));
    }

    #[test]
    fn validation_clamps() {
        let mut s = load_from(json!({"scale":9,"opacity":0.01,"sound":{"volume":4},"overheatKps":0}));
        assert_eq!(s["scale"], 4);
        assert_eq!(s["opacity"], 0.2);
        assert_eq!(s["sound"]["volume"], 1.0);
        assert_eq!(s["overheatKps"], 1.0);
        s["scale"] = json!(2.6);
        validate(&mut s);
        assert_eq!(s["scale"], 3);
        s["scale"] = json!("junk");
        validate(&mut s);
        assert_eq!(s["scale"], 2);
    }

    #[test]
    fn updates_auto_defaults_on_and_junk_is_repaired() {
        assert_eq!(load_from(json!({}))["updates"]["auto"], true);
        assert_eq!(load_from(json!({"updates":{"auto":false}}))["updates"]["auto"], false);
        assert_eq!(load_from(json!({"updates":{"auto":"yes"}}))["updates"]["auto"], true);
    }

    #[test]
    fn load_fills_missing_keys_and_keeps_user_values() {
        let s = load_from(json!({"userName":"Ada","palettes":{"stitch":{"body":"#000000"}}}));
        assert_eq!(s["userName"], "Ada");
        assert_eq!(s["palettes"]["stitch"]["body"], "#000000");
        assert_eq!(s["palettes"]["stitch"]["outline"], "#1b2a5c");
        assert_eq!(s["reminders"]["water"]["everyMin"], 40);
        assert_eq!(load_from(json!("garbage"))["version"], 1);
    }
}
